# use onbuild variant, this will automatically copies the package source,
# fetches the application dependencies, builds the program,
# and configures it to run on startup
FROM golang:1.7.4-onbuild

MAINTAINER Zhang Wenqing "winking.zhang@grapecity.com"

EXPOSE 8081